version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: sprc/flask_live_app:1.0.0
    build: .
    ports:
      - "6000:6000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    restart: always
    ports:
      - '8978:8978'
    volumes: 
      - cloudbeaver:/opt/cloudbeaver/workspace 

volumes:
  pgdata: {}
  cloudbeaver: {}
    