version: "3.9"

networks:
  app_net:
  beaver_net:

services:
  flask_app:
    container_name: flask_app
    restart: always
    build: .
    image: sprc/flask_live_app:1.0.0
    ports:
      - "6000:6000"
    environment:
      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
    networks:
      - app_net
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    restart: always
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_net
      - beaver_net
  cloudbeaver:
    image: dbeaver/cloudbeaver:latest
    container_name: dbeaver
    restart: always
    ports:
      - '8978:8978'
    environment:
      - CB_ADMIN_NAME=cbadmin
      - CB_ADMIN_PASSWORD=cbadmin
    volumes: 
      - cloudbeaver:/opt/cloudbeaver/workspace
    networks:
      - beaver_net
    depends_on:
      - flask_db

volumes:
  pgdata: {}
  cloudbeaver: {}
    