/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUM_H_RPCGEN
#define _SUM_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct sum {
	int x;
	int y;
};
typedef struct sum sum;

#define CHECKPROG 0x31234567
#define CHECKVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_SUM 1
extern  int * get_sum_1(sum *, CLIENT *);
extern  int * get_sum_1_svc(sum *, struct svc_req *);
extern int checkprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_SUM 1
extern  int * get_sum_1();
extern  int * get_sum_1_svc();
extern int checkprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_sum (XDR *, sum*);

#else /* K&R C */
extern bool_t xdr_sum ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUM_H_RPCGEN */
