/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sum.h"


void
checkprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	sum  get_sum_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CHECKPROG, CHECKVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("Enter value for x = ");
	scanf("%d", &get_sum_1_arg.x);
	printf("Enter value for y = ");
	scanf("%d", &get_sum_1_arg.y);
	result_1 = get_sum_1(&get_sum_1_arg, clnt);
	printf("The sum is: %d\n", *result_1);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	checkprog_1 (host);
exit (0);
}
