/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "tema1.h"

bool_t
xdr_request_access_arg (XDR *xdrs, request_access_arg *objp)
{
	 int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->request_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->with_refresh))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_request_access_response (XDR *xdrs, request_access_response *objp)
{
	 int32_t *buf;

	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->refresh_token, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->error_message, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->error_flag))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_action_arg (XDR *xdrs, validate_action_arg *objp)
{
	 int32_t *buf;

	 if (!xdr_string (xdrs, &objp->operation, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->resource, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->access_token, ~0))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_validate_action_response (XDR *xdrs, validate_action_response *objp)
{
	 int32_t *buf;

	 if (!xdr_string (xdrs, &objp->result, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->new_access_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->access_token_refreshed))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_approve_request_response (XDR *xdrs, approve_request_response *objp)
{
	 int32_t *buf;

	 if (!xdr_string (xdrs, &objp->request_token, ~0))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->with_sign))
		 return FALSE;
	return TRUE;
}
